#!/bin/sh

# THIS SCRIPT JUST CREATES THE REINDEX_FILE WHICH WILL PREVENT RE-INDEXING FOR HAPPENING ON A NEWLY INITIALISED DB


if [ -n "$OR_REINDEX_COUNTER" ]; then
    REINDEX_FILE="$PGDATA/OR_REINDEX_COUNTER.$OR_REINDEX_COUNTER"
    echo "Creating REINDEX_FILE '$REINDEX_FILE'"...
    touch "$REINDEX_FILE"
fi
